encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.openTitle, name= "openTitle")
]

wiki/encyclopedia/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from datetime import datetime
from http.client import HTTPResponse
from django.shortcuts import render
import datetime
import markdown
from django.http import HttpResponse

from . import util

def index(request):
    # Check if method is post
    if request.method == "POST":
        title = None
        if 'q' in request.POST:
            title = request.POST.get("q")
        elif 'submit_param' in request.POST:
            title = request.POST.get("submit_param")
        #Fetch the entry
        entry = util.get_entry(title)

        #Check if entry is valid
        if util.get_entry(title) != None:

            #Create html from markdown
            html = markdown.markdown(entry)
            return HttpResponse(f"{html}")
        else:

            #Print error
            return HttpResponse("<h1>The page does not exist</h1>")
    
            

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def openTitle(request, title):
     #Check if entry is valid
    if util.get_entry(title) != None:

        #Create html from markdown
        html = markdown.markdown(entry)
        return HttpResponse(f"{html}")
    else:

        #Print error
        return HttpResponse("<h1>The page does not exist</h1>")

wiki/encyclopedia/views.py
from django.shortcuts import render

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <div>
        demo changes 2
    </div>
    <ul>
        {% for entry in entries %}
        <li>
            <form method="post" action="{% url 'encyclopedia:index' %}" class="inline">
                {% csrf_token %}
                <button type="submit" name="submit_param" value="{{entry}}" class="link-button">
                {{entry}}
                </button>
            </form>
        </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <style>
            .inline {
                display: inline;
            }

            .link-button {
                background: none;
                border: none;
                color: blue;
                text-decoration: underline;
                cursor: pointer;
                font-size: 1em;
                font-family: serif;
            }
            .link-button:focus {
                outline: none;
            }
            .link-button:active {
                color:red;
            }
        </style>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action = "{% url 'encyclopedia:index'  %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" >
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    Create New Page
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
        <div>
            This is a demo
        </div>
    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    Create New Page
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>